version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: statistique_service
    restart: always
    environment:
      POSTGRES_USER: imt
      POSTGRES_PASSWORD: imt
      POSTGRES_DB: statistique_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
