version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: statistique_service
    restart: always
    environment:
      POSTGRES_USER: imt
      POSTGRES_PASSWORD: imt
      POSTGRES_DB: statistique_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  statistique-service:
    build: .
    container_name: statistique-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "npx prisma migrate deploy && npm run seed && npm run dev" ]

volumes:
  postgres_data:
